apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: taskflow-frontend-hpa
  namespace: taskflow
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: taskflow-frontend-deployment

  minReplicas: 2
  maxReplicas: 5

  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

  - type: Pods 
    pods:
      metric:
        name: packets-per-second
      target:
        type: AverageValue
        averageValue: 1000

  behavior:
    scaleUp:
      policies:
      - type: Pods
        value: 2
        periodSeconds: 60

    scaleDown:
      stabilizationWindowSeconds: 200
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60
    