apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  name: pvc-taskflow
  namespace: taskflow
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  volumeName: pv-taskflow

  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  name: pvc-redis-taskflow
  namespace: taskflow
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

  
