name: Dependency scan

on:
  workflow_call:

jobs:
  dependency-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      ###### Generate JSON report #######

      # - name: Run Trivy vulnerability scanner in fs mode
      #   uses: aquasecurity/trivy-action@v0.36.0
      #   with:
      #     scan-type: 'fs'
      #     scan-ref: '.'
      #     trivy-config: trivy.yml
      #     format: json
      #     output: trivy-results.json
      
      # - name: Upload Trivy Scan Result
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with: 
      #     name: trivy json results
      #     path: trivy-results.json
      #     retention-days: 7

      ###### Generate SARIF report #######
      
      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          trivy-config: trivy.yml
          format: sarif
          output: trivy-results.sarif 

      - name: Upload Trivy scan results to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-results.sarif'