name: taskflow ci pipeline

on:
  push:
    branches:
      - feat/github-actions

jobs:
  code-quality:
    uses: ./.github/workflows/code-quality.yml

  dependency-security:
    permissions:
      contents: read
      security-events: write
    uses: ./.github/workflows/dependency-security.yml

  